Recruitment web app - Account #11
HopeeSolutionsRuby/demo-app pull request #17
Opened 2023-07-07 10:45 UTC by longhoangcoder

issue 11: https://github.com/HopeeSolutionsRuby/demo-app/issues/11
description: 
- setup account file using devise gem
- upload avatar feature using carrierwave gem
- implement redirect after login for each roles

2023-07-10 02:46 UTC, KhoaNDAHopee requested changes
- Check conflict ruby version in Gemfile, .ruby-version
- Implement ``forgot password``
- Show error when input invalid email/password

2023-07-10 02:46 UTC, KhoaNDAHopee commented on app/controllers/admin/dashboard_controller.rb
> +module Admin
Should use plural

2023-07-10 02:46 UTC, KhoaNDAHopee commented on app/controllers/employee/dashboard_controller.rb
> +module Employee
Should use plural

2023-07-10 02:46 UTC, KhoaNDAHopee commented on app/controllers/employer/dashboard_controller.rb
> +module Employer
Should use plural

2023-07-10 02:46 UTC, KhoaNDAHopee commented on app/models/account.rb
> +  def downcase_email
Research about devise configs ``config.case_insensitive_keys = [:email]``

2023-07-10 02:46 UTC, KhoaNDAHopee commented on app/uploaders/avatar_uploader.rb
> +  storage :file
Set global config ``config/initializers/carrierwave.rb``

2023-07-10 02:46 UTC, KhoaNDAHopee commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }
Set configs for https://github.com/ryanb/letter_opener, https://github.com/fgrehm/letter_opener_web
(fake mail server for development)

2023-07-11 02:20 UTC, DucNguyen0812 commented
LGTM!

2023-07-11 02:21 UTC, DucNguyen0812 approved these changes

2023-07-11 02:44 UTC, Priyarekah approved these changes
I tested it and it is fine with me.

2023-07-11 02:48 UTC, KhoaNDAHopee approved these changes
LGTM

2023-07-11 02:48 UTC, merged