Recruitment web app - administrator - CRUD employee #18
HopeeSolutionsRuby/demo-app pull request #26
Opened 2023-07-17 01:49 UTC by jjjsss3

Issue: https://github.com/HopeeSolutionsRuby/demo-app/issues/18
Description: 
- Migrate create model employee
- Admin Employee Controller for CRUD
- View for CRUD

Note (optional): 
- Have used pagy for pagination, ransack for search, turbo-rails for ajax
-  Have not yet shown the avatar on the view (can select to create and update)

2023-07-17 08:32 UTC, tunh-dev1 approved these changes
LGTM!

2023-07-18 03:17 UTC, KhoaNDAHopee requested changes

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/controllers/admins/employees_controller.rb
> +      @url = admins_employees_path
No need to assign this variable to views

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/controllers/admins/employees_controller.rb
> +      @queries = 'id_or_first_name_or_last_name_or_address_or_account_email_or_account_phone_cont'
No need to assign this variable to views

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/controllers/admins/employees_controller.rb
> +      @employees = @q.result(distinct: true)
No need to assign this variable to views

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/controllers/admins/employees_controller.rb
> +      employees = employee_current_before_after_get
Don't load 3 employees every go to detail page, only load 1

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/models/concerns/capitalizable.rb
> +    def capitalize_attribute(attribute)
No need

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/models/concerns/employee_activities.rb
> +    capitalize_attribute :first_name
No need

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/models/concerns/employee_activities.rb
> +    capitalize_attribute :last_name
No need

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/models/concerns/employee_activities.rb
> +    def self.create_with_account(params)
Move it to services https://viblo.asia/p/rails-service-objects-guide-bWrZnNkmZxw

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/models/concerns/employee_activities.rb
> +  def send_email_register
No need

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/admins/employees/_table.html.erb
> +      <th scope="col"><%= sort_link(@q, :id, "#", class: 'text-dark text-decoration-none')  %></th>
``one') %>`` check spacing, check another.

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/admins/employees/_table_line.html.erb
> +  <th scope="row"><%= employee.id%></th>
``id%>`` spacing

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/admins/employees/edit.html.erb
> +  <%# First name, last name %>
No need to use ruby comments

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/admins/employees/new.html.erb
> +    <%= form.file_field :avatar, class:"form-control mb-2", id:"formFileSm"%>
- ``id:"formFileSm"`` spacing
- Follow naming conventions for id, class =>`` form-file-sm``, check another

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/shared/_pagination.html.erb
> +<%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 0 %>
- ``<%==``
- Don't show pagination if page = 1

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/shared/_search_box.html.erb
> +    <%= search_form_for @q, url: @url, remote: true, data: { turbo_frame: 'container-frame' } do |f| %>
``@url`` Use view helpers instead get instance variable from controller

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/shared/admin/_left_menu.html.erb
> +    <a class="nav-link row d-flex" role="button" data-toggle="collapse" data-target="#collapse_accounts" aria-expanded="true" aria-controls="collapse2">
Use view helpers

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/shared/admin/_left_menu.html.erb
> +    <a class="nav-link row d-flex" role="button" data-toggle="collapse" data-target="#collapse_employers" aria-expanded="true" aria-controls="collapse2">
Use view helpers

2023-07-18 03:17 UTC, KhoaNDAHopee commented on app/views/shared/admin/_left_menu.html.erb
> +    <a class="nav-link row d-flex" role="button" data-toggle="collapse" data-target="#collapse_employees" aria-expanded="true" aria-controls="collapse2">
Use view helpers

2023-07-18 03:17 UTC, KhoaNDAHopee commented on config/initializers/pagy.rb
> +Pagy::DEFAULT[:size]  = [1,4,4,1]
Check code style

2023-07-18 08:55 UTC, DucNguyen0812 approved these changes
LGTM!

2023-11-29 06:54 UTC, closed without merging