[Issue 33]: Implement admin layout
HopeeSolutionsRuby/demo-app pull request #38
Opened 2023-12-04 10:03 UTC by khoadev2512

## Issue
- Connect #ISSUE_NUMBER ([Related Issue)](https://github.com/HopeeSolutionsRuby/demo-app/issues/33)

## ToDo
- [x] Task No.1:  Implement header
- [x] Task No.2: Implement sidebar 

## Self-Review
### Coding Style
- [x] Check rubocop

## Test Result
- screenshot:
![image](https://github.com/HopeeSolutionsRuby/demo-app/assets/85111677/1084e316-b7e0-4cb0-963b-93673160a971)

# ** Note
link test: http://localhost:3000/administrator/dashboard

2023-12-04 10:24 UTC, hothanhdatsd approved these changes

2023-12-04 10:27 UTC, PhiH-XDev approved these changes

2023-12-04 10:30 UTC, minhnguyennn approved these changes

2023-12-06 02:40 UTC, KhoaNDAHopee requested changes

2023-12-06 02:40 UTC, KhoaNDAHopee commented on Gemfile
> +gem 'devise', '~> 4.9'
For what?

2023-12-06 02:40 UTC, KhoaNDAHopee commented on app/assets/stylesheets/administrator/header.scss
Check spacing, endline

2023-12-06 02:40 UTC, KhoaNDAHopee commented on app/assets/stylesheets/fonts.scss
Check spacing

2023-12-06 02:40 UTC, KhoaNDAHopee commented on app/controllers/administrator_controller.rb
For what?

2023-12-06 02:40 UTC, KhoaNDAHopee commented on app/javascript/controllers/admin_controller.js
Check spacing, endline

2023-12-06 02:40 UTC, KhoaNDAHopee commented on app/views/administrator/dashboard/_body.html.erb
> +                        <i class="fa-solid fa-user-doctor" style="margin-left: 3px;"></i> <span class="ms-2 d-sm-inline">Doctors</span></a>
Check spacing and closing tags
```
<a>
  abc
</a>
or
<a>abc</a>
```

2023-12-07 02:26 UTC, KhoaNDAHopee requested changes

2023-12-07 02:26 UTC, KhoaNDAHopee commented on app/javascript/controllers/admin_controller.js
> +  });
Spacing

2023-12-07 02:26 UTC, KhoaNDAHopee commented on app/views/layouts/admin.html.erb
> +              <div style="min-height: 90vh; width: 100%">
Don't use inline css

2023-12-07 02:26 UTC, KhoaNDAHopee commented on app/views/shared/administrator/_footer.html.erb
> +<div style="position: absolute; bottom: 0;border-top: 1px solid #dbdee4; padding-bottom:7px;padding-top:7px; text-align:center" class="w-100">Thank you for creating with Phoenix|2023 ©Themewagon </di
Don't use inline css

2023-12-07 04:08 UTC, closed without merging