Issue 36 implement authentication customer khoa
HopeeSolutionsRuby/demo-app pull request #47
Opened 2023-12-11 01:55 UTC by khoadev2512

## Issue
- Connect #ISSUE_NUMBER (Related Issue)

## ToDo
- [ ] Task No.1: Login / logout
- [ ] Task No.2: Sign up
- [ ] Task No.3: Reset password

## Self-Review
### Coding Style
- [ ] Check rubocop

# ** Note

2023-12-11 06:16 UTC, hothanhdatsd approved these changes

2023-12-12 10:39 UTC, KhoaNDAHopee requested changes

2023-12-12 10:39 UTC, KhoaNDAHopee commented on app/assets/stylesheets/sign_up.scss
Check endline

2023-12-12 10:39 UTC, KhoaNDAHopee commented on app/controllers/customers/registrations_controller.rb
Remove unused code, don't comment these, check another place

2023-12-13 07:52 UTC, KhoaNDAHopee approved these changes

2023-12-13 07:52 UTC, merged