Issue 35 implement authen admin
HopeeSolutionsRuby/demo-app pull request #48
Opened 2023-12-11 02:23 UTC by minhnguyennn

## Issue
- Connect #ISSUE_NUMBER (Related Issue)

## ToDo
- [ ] Task No.1 : Authen sign-in/out with by username
- [ ] Task No.2 : Authen reset passsword with by email

## Self-Review
### Coding Style
- [ ] Check rubocop

### Specs Checking
- [ ] Run rspec

## Test Result
- screenshots, videos

# ** Note

2023-12-11 03:10 UTC, KhoaNDAHopee requested changes

2023-12-11 03:10 UTC, KhoaNDAHopee commented on app/assets/stylesheets/administrator/forgot_password.scss
> +.fullVH {
Follow naming conventions https://courses.cs.washington.edu/courses/cse154/17au/styleguide/html-css/naming-conventions-html.html, check another place

2023-12-11 03:10 UTC, KhoaNDAHopee commented on app/views/administrator/unlocks/new.html.erb
> +<<<<<<< HEAD
What is this?

2023-12-11 03:10 UTC, KhoaNDAHopee commented on app/views/administrator/unlocks/new.html.erb
Remove unused views, check another place

2023-12-11 03:10 UTC, KhoaNDAHopee commented on config/environments/development.rb
Don't use this config for development

2023-12-11 03:10 UTC, KhoaNDAHopee commented on app/controllers/administrator/passwords_controller.rb
Remove unused controller, check another.

2023-12-11 03:10 UTC, KhoaNDAHopee commented on app/models/admin.rb
How about unit test?

2023-12-11 06:10 UTC, khoadev2512 approved these changes

2023-12-13 10:57 UTC, KhoaNDAHopee approved these changes

2023-12-13 10:57 UTC, merged